apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: shoppy
spec:
  selector:
    app: shoppy-frontend
    kubernetes.io/name: frontend
    kubernetes.io/part-of: shoppy
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000