---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: shoppy
spec:
  selector:
    shoppy.io/name: shoppy-frontend
    app.kubernetes.io/name: shoppy-frontend
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80